package com.yourname.simpletranslate.gui;

import com.yourname.simpletranslate.config.ModConfig;
import com.yourname.simpletranslate.translation.TranslationEngine;
import net.minecraft.client.gui.GuiScreen;

final class TooltipGlowSettingsScreen extends ScrollableSettingsScreen {
    TooltipGlowSettingsScreen(GuiScreen parent,TranslationEngine engine){super(parent,engine,"screen.simple_translate.tooltip_glow.feature","screen.simple_translate.main.glow");}
    @Override protected void buildContent(){int y=0;addContentTextButton(100,y,stateLabel("screen.simple_translate.tooltip_glow.enabled",ModConfig.TOOLTIP_GLOW_ENABLED.get()),"screen.simple_translate.tooltip_glow.enabled.tooltip");y+=26;addContentTextButton(101,y,tr("screen.simple_translate.tooltip_glow.line_width")+": "+tr("screen.simple_translate.tooltip_glow.pixels",ModConfig.TOOLTIP_GLOW_LINE_WIDTH.get()),"screen.simple_translate.tooltip_glow.line_width.tooltip");y+=26;addContentTextButton(102,y,tr("screen.simple_translate.tooltip_glow.spread")+": "+tr("screen.simple_translate.tooltip_glow.pixels",ModConfig.TOOLTIP_GLOW_SPREAD.get()),"screen.simple_translate.tooltip_glow.spread.tooltip");y+=26;addContentTextButton(103,y,tr("screen.simple_translate.tooltip_glow.speed")+": "+tr("screen.simple_translate.tooltip_glow.seconds_decimal",ModConfig.TOOLTIP_GLOW_CYCLE_MS.get()/1000.0D),"screen.simple_translate.tooltip_glow.speed.tooltip");y+=26;addContentTextButton(104,y,tr("screen.simple_translate.tooltip_glow.opacity")+": "+tr("screen.simple_translate.tooltip_glow.percent",Math.round(ModConfig.TOOLTIP_GLOW_OPACITY.get()*100F/255F)),"screen.simple_translate.tooltip_glow.opacity.tooltip");y+=26;addContentTextButton(105,y,tr("screen.simple_translate.tooltip_glow.theme")+": "+tr("screen.simple_translate.tooltip_glow.theme."+ModConfig.TOOLTIP_GLOW_THEME.get().name().toLowerCase(java.util.Locale.ROOT)),"screen.simple_translate.tooltip_glow.theme.tooltip");setContentHeight(y+30);}
    @Override protected boolean onContentButton(int id){if(id==100)ModConfig.TOOLTIP_GLOW_ENABLED.set(!ModConfig.TOOLTIP_GLOW_ENABLED.get());else if(id==101)ModConfig.TOOLTIP_GLOW_LINE_WIDTH.set(ModConfig.TOOLTIP_GLOW_LINE_WIDTH.get()>=6?1:ModConfig.TOOLTIP_GLOW_LINE_WIDTH.get()+1);else if(id==102)ModConfig.TOOLTIP_GLOW_SPREAD.set(ModConfig.TOOLTIP_GLOW_SPREAD.get()>=12?0:ModConfig.TOOLTIP_GLOW_SPREAD.get()+1);else if(id==103)ModConfig.TOOLTIP_GLOW_CYCLE_MS.set(ModConfig.TOOLTIP_GLOW_CYCLE_MS.get()>=24000?2000:ModConfig.TOOLTIP_GLOW_CYCLE_MS.get()+1000);else if(id==104)ModConfig.TOOLTIP_GLOW_OPACITY.set(ModConfig.TOOLTIP_GLOW_OPACITY.get()>=255?20:Math.min(255,ModConfig.TOOLTIP_GLOW_OPACITY.get()+15));else if(id==105){ModConfig.TooltipGlowTheme[] values=ModConfig.TooltipGlowTheme.values();ModConfig.TOOLTIP_GLOW_THEME.set(values[(ModConfig.TOOLTIP_GLOW_THEME.get().ordinal()+1)%values.length]);}else return false;ModConfig.save();if(engine!=null)engine.setTooltipGlowEnabled(ModConfig.TOOLTIP_GLOW_ENABLED.get());return true;}
}
